---
title: "Probability distributions"
format: html
---

Biological systems are variable, and we consequently need statistical methods to cope with this variability in drawing valid inferences from our data. As a consequence of this variability, we can never say anything with *absolute* certainty based on biological data: there will always be some “doubt” due to **chance variation**. Not surprisingly, we need the tools and language of probability to assist us with quantifying our level of “doubt” when we make our conclusions.

:::{.callout-note}
We won't deal with probability theory to any great degree in this unit of study, but just outline some of the key HSC Maths concepts that we will build on.
:::

## Probability

### Simple probability

The probability of an event is the proportion of times that the event occurs in a large number of repeated trials. For example, if we toss a coin 100 times, we would expect to get 50 heads and 50 tails. The probability of getting a head is therefore 0.5.

The equation for probability is:

:::{.callout-important appearance="minimal"}
$$ P(E) = \frac{\text{number of times event E occurs}}{\text{total number of trials}} $$ 
:::

where:

- $P(E)$ is the probability of event $E$,
- $P(E) = 0$ the event is impossible, and
- $P(E) = 1$ the event is certain (must happen).

:::{.callout-tip}
## Exercise
A person is chosen at random to write about his/her favourite sport. Thirty-five people like tennis, 51 like cricket, 17 like squash, 23 like baseball and 62 like swimming. Find the probability that the article will be about:

a) Swimming.
b) Squash or tennis.
:::

:::{.callout-tip appearance="simple" collapse="true"}
## Answer

a. $P(\text{swimming}) = 62/188 = 0.33$
b. $P(\text{squash or tennis}) = (35 + 17)/188 = 0.28$
:::

### Complementary events

Probability of an event not occurring is called the **complementary event**, $P(\tilde{E})$. The probability of an event occurring plus the probability of the complementary event occurring is 1. That is:

$$ P(E) + P(\tilde{E}) = 1 $$

or:

$$ P(\tilde{E}) = 1 - P(E)$$

:::{.callout-tip}
## Exercise

a. The proability of rain on 23 January each year is $17/53$. What is the probability of no rain on 23 January, 2023?

b. The probability of a person being left-handed is $0.13$. What is the probability of a person being right-handed?

:::


### Non-Mutually Exclusive Events